Description: >
  Api Gateway with Lambda function

Parameters:
  BucketName:
  Type: String
  Description: code bucket

  BucketKey:
  Type: String
  Description: zip name

Resources:
  Function:
    Type: "AWS::Lambda::Fuction"
    Properties:
      Handler: "main.run"
      Role:
        Fn::GetAtt:
          - "LambdaExecutionRole"
          - "Arn"
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !Ref BucketKey
      Runtime: "python3.8"
      Timeout: 25